#version: '3.8'
#services:
#  mongodb-1:
#    image: mongo
#    command: "--auth"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
#    ports:
#      - "27017:27017"
#    volumes:
#      - ./data:/data/db
